### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by pbelange** [ColasDroin/simulation-dashboard#1]
1. Did not work with package versions in requirement.txt for python 3.12.0, had to remove all version information from all packages to get pip to properly install

2.  Installme.sh should include collider_check:
```bash
pip install -r requirements.txt
mkdir modules
cd modules
git clone https://github.com/xsuite/xmask.git
pip install -e xmask
cd xmask
git submodule init
git submodule update
cd ..
git clone https://github.com/PyCOMPLETE/FillingPatterns.git
pip install -e FillingPatterns
git clone https://github.com/ColasDroin/twiss_check.git
git clone https://github.com/ColasDroin/build_collider.git
git clone https://github.com/ColasDroin/collider_check.git
cd ..
xsuite-prebuild
```

**Comment by ColasDroin** [comment]
Thanks for signalling.

1. This is due to regular Xsuite upgrades. I removed the versions from the requirements file for Xsuite packages accordingly.
2. Good catch, corrected. Also removed the (now deprecated) twiss_check.

**Comment by pbelange** [comment]
1. Not only xsuite, for example `numpy==1.25.1` does not work with python 3.12 apparently

**Comment by ColasDroin** [comment]
I've made a note of that, thanks. I'm removing all packages' versions until I do proper testing.
